2020-04-23 20:29:14.095 [error] <0.522.0> CRASH REPORT Process <0.522.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-ES,es;q=0.9,en;q=0.8,und;q=0.7,it;q=0.6">>,<<"cache-control">> => <<"no-cache">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"loc...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87
2020-04-23 20:29:14.127 [error] <0.522.0> Cowboy stream 1 with ranch listener 'Elixir.Microservice1Web.Endpoint.HTTP' and connection process <0.521.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"es-ES,es;q=0.9,en;q=0.8,und;q=0.7,it;q=0.6">>,<<"cache-control">> => <<"no-cache">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"loc...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 87
